repos:
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
        exclude: '(^.vscode/)'
      - id: pretty-format-json
        exclude: '(^.vscode/)'
        args:
          - --autofix
          - --indent
          - '2'
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==22.3.0]
      - id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==2.7.3]
      - id: nbqa-isort
        additional_dependencies: [isort==5.6.4]
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: ['--profile', 'black']
