repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
          - --indent
          - '2'
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==20.8b1]
      - id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==2.7.3]
      - id: nbqa-isort
        additional_dependencies: [isort==5.6.4]
