[tool.poetry]
authors = ["tqtensor <victortang212@gmail.com>"]
description = "Prompt Optimization Workshop"
name = "vn-ds"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
openai = "^1.59.7"
python = "^3.11"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"
toml-sort = "^0.23.1"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
